### ISSUE TITLE
Date picker stuck on February 2016, then freezes

### ISSUE THREAD

**Issue by jsbono** [rajit/bootstrap3-datepicker#21]
I'm using this meteor package, with the below code. I can select a date for January which works as expected - date set in input form and the date picker closes, but if I choose a date before or after January, the date picker displays only one month forwards or backwards (February or November) then the package locks up and does not display months forward or backwards and it will not autoclose. I searched stack overflow for solutions, but could not find one. Thoughts?

template:
       ` <div class="form-group">
        <label id="dueDate" class="col-sm-3 control-label" for="dueDate">Due Date</label>
        <div class="col-sm-9">
          <input class="form-control" data-provide="datepicker" id="datepicker" name="dueDate" type="text" value="" placeholder="Choose Due Date">
        </div>
      </div>`

JS file:
  `$('#datepicker').datepicker({
    format: "mm-dd-yy",
    autoclose: true
  });`

**Comment by rajit** [comment]
I've used your code in this sample repository: https://github.com/rajit/b3dp-21

I'm not able to see the issue you describe when I run this. Could you try cloning and running the above repository and then try to recreate the issue?

If you need to make any code changes in order to recreate the issue, please fork the repository, commit your changes and share the repository here.

**Comment by rajit** [comment]
It's not 100% clear to me if you've got this working now.

I'll close the issue — but please re-open it with the latest information if it is still a problem for you.
