### ISSUE TITLE
Reactive rerender of datepicker on language selection

### ISSUE THREAD

**Issue by janat08** [rajit/bootstrap3-datepicker#27]
With tracker depends maybe you could implement i18n rerendering since that rerenders template.

**Comment by rajit** [comment]
Hi janat08,

Could you explain a little more what you mean? Perhaps by giving me an example in code.

**Comment by janat08** [comment]
https://github.com/janat08/hotel/blob/master/imports/ui/calendar.js
Is a silly implementation of switching languages with tap i18n, and be weary of the fact that changing language doesn't instantly mean that getTapi18n language something command will be the right one (thus I hooked it to change language event with intention of also hooking to language detection rather than using actual api). Reading Tracker wiki on github they have Tracker dependons for package authors that should serve as session.get.

**Comment by rajit** [comment]
Right now this is a very light wrapper around eternicode/bootstrap-datepicker. It's not obvious to me right now what change to make, partially because I still fully understand your example but also because I have a feeling I may need to change the way the wrapper works.

If you're so inclined, please do make a pull request for this feature. So long as the wrapper still serves its current purpose I'm open to a change like this. I would review your pull request, possibly modify it and if all looks good accept it.

**Comment by janat08** [comment]
I may not do that, but ultimately the point is to switch languages prolly
setting up a bridge to hook i18n with calendar i18n. I'm a newbie as well.

**Comment by rajit** [comment]
I'm going to close this as "wontfix", but I'm welcome to PRs.
